# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='correct_word',
            field=models.CharField(max_length=128, null=True, verbose_name='correct'),
        ),
    ]
