# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20160819_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='correct_word',
            field=models.CharField(blank=True, max_length=128, verbose_name='correct'),
        ),
    ]
