# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20160823_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordrecord',
            options={'verbose_name': 'wordRecord', 'verbose_name_plural': 'wordRecords'},
        ),
        migrations.AlterModelOptions(
            name='wordtest',
            options={'ordering': ['test_date'], 'verbose_name': 'WordTest', 'verbose_name_plural': 'WordTests'},
        ),
        migrations.AlterField(
            model_name='wordrecord',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.Word'),
        ),
    ]
